### PR TITLE
Support set variable

### PR DESCRIPTION
**Pull request by zero-plusplus**
**By Google Translate from Japanese to English.**

## Known issues
The following issues arose in Node debugging as well.
In other words, it depends on my environment or it is a vscode specification.
The confirmed version of vscode is 1.44.0.

### Replacement of variables when an error occurs
If an error occurs when rewriting a variable, the variable name and value are temporarily replaced with another variable. This does not overwrite the actual value.

Occurs when you call setErrorResponse.

### Line breaks are lost when edited
The line break disappears when you edit a string that contains a line break. Even if it is not edited, it will disappear if you press Enter.

Also, the display becomes strange if you cancel it with Escape without editing.

### CODE REVIEW

**Comment by cweijan** [comment]
When I type string without quote, It will fail.
image

**Comment by zero-plusplus** [comment]
**By Google Translate from Japanese to English.**

I'm sorry. I should have explained the rewriting rules.

In conclusion, that behavior is normal.
When setting the value as a character string, it must be enclosed in double quotes.

The rules for rewriting variables follow the Node debugger.
According to it, there are probably three types of rewritable values: strings, numbers and variable names.
In this case, it is treated as a variable name. The value is in `match [6]` instead of `str`.

Setting the value by variable name is not supported, so an error should occur there.

**Comment by cweijan** [comment]
I changed [matchRule](https://github.com/cweijan/vscode-autohotkey/blob/b43c0222e34b422a6a924140189cab589d66443b/src/debugger/AhkRuntime.ts#L194), you can review it, if have any problem, change it and create PR.

**Comment by zero-plusplus** [comment]
**By Google Translate from Japanese to English.**

Automatic double quotes can be confusing for people using the "Node Debugger".
Also, if we now support rewriting values by variable name, the rewriting rules will be inconsistent.

That said, I accept this change.
Because I never use this function.

**Comment by cweijan** [comment]
The node debug program is the same as you said, You are right, rollback for your  version.

**Comment by cweijan** [comment]
Now it support set variable value by another variable name and update to 2.3.3, thanks for contribute.
Sorry.. now it's 2.3.4

**Comment by zero-plusplus** [comment]
**By Google Translate from Japanese to English.**

It is good to create `sendComandSync` function to implement variable name rewriting.

It can be useful when implementing conditional breakpoints in the future.
I stopped making it because it wasn't there.

The reason I didn't make it myself is that I usually only use AutoHotkey, so I'm not familiar with async.

**Comment by cweijan** [comment]
I did a simple code refactoring, now can using async await convert async to sync, reference [stack](https://github.com/cweijan/vscode-autohotkey/blob/fd07d9f1ecb3c3e9c8872cd2d91033d683323830/src/debugger/AhkRuntime.ts#L287) code

**Comment by zero-plusplus** [comment]
**By Google Translate from Japanese to English.**

Thank you.
I am going to use it as an example.

It's a bit different to talk about here, but let's talk about conditional breakpoints. Because I may not start right away.

Unfortunately AutoHotkey itself does not support [conditional breakpoints](https://github.com/Lexikos/AutoHotkey_L/blob/master/source/Debugger.cpp#L605).

So we need a way to evaluate the expression.

There are the following two approaches.
* [How to output to stdout of AutoHotkey.exe and get it](https://www.autohotkey.com/docs/commands/Run.htm#ExecScript) (It can be treated as a real eval function)
* How to evaluate an expression in JavaScript

The first advantage is that you can use the same syntax. However, the problem is to start the exe every time. It should also be noted that arbitrary code can be executed.
The second advantage is that it operates fast and is easy to implement. You can pass properties differently than the first method. And you can [Safely Evaluate](https://www.npmjs.com/package/safe-eval). However, many people will be confused by the change in syntax.

It is ideal to implement both of the two methods so that they can be selected in the configuration file, but I think that it is sufficient to implement the second method and write a note in Readme.md.

**Comment by cweijan** [comment]
The second way is obviously better.

**Comment by cweijan** [comment]
By Google Translate from Chinese to English.
I will not participate in the development of conditional breakpoints. In fact, I rarely use debug programs, I just implement it, which is a sense of accomplishment.

**Comment by zero-plusplus** [comment]
I understand.

**Comment by cweijan** [comment]
Unfortunately, the refactored code caused the plug-in exception and I had to go back to before the version.

**Pull request merged**
