### PR TITLE
Support level down stack variable

### PR DESCRIPTION
**Pull request by zero-plusplus**

### CODE REVIEW

**Comment by cweijan** [comment]
I saw the feature you added, I need time to handle .

**Comment by zero-plusplus** [comment]
**By Google Translate from Japanese to English.**

### Known issues:
If the array exceeds 100, "[0..99]" will be displayed in the debug UI.
Since the sequence of Autohotkey starts from 1, "[1..100]" is desirable.

But I don't know how to change it.

The definition of the format "[0..99]" is probably done by ExpressionContainer's doGetChildren method.
* https://github.com/microsoft/vscode/blob/c033ceaa241f8bf94e2661ee5c4adb7f9af86be0/src/vs/workbench/contrib/debug/common/debugModel.ts#L89

And "startOfVariables", which represents the starting number, is set by the constructor. The default value is 0.
* https://github.com/microsoft/vscode/blob/c033ceaa241f8bf94e2661ee5c4adb7f9af86be0/src/vs/workbench/contrib/debug/common/debugModel.ts#L45

However, "startOfVariables" is never passed to the ExpressionContainer or child class constructor.
Therefore, since "0" is always set, the notation of "[0..99]" cannot be changed at present.

that's all.

**Comment by cweijan** [comment]
Your feature is perfect, added to 2.3.0.

**Comment by zero-plusplus** [comment]
Thanks!

**Pull request merged**
